
sub1: '<import>sub1.yaml'
sub2: '<import>sub1.yaml'

some_param: 'some_value'
some_ref_param: '<ref>main_system/some_values[2]'

this_also_works: '<ref>sub1/some_param'
this_is_different: '<ref>sub2/some_param'

main_system: {
  some_values: [0,1,2,3,4]
}